version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: PayWave/Dockerfile
    depends_on:
        - db
    ports:
        - "8080:80"
        - "8081:433"
    environment:
        - CircleAPIKey=CircleAPIKeyFromCircleWeb

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"